//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CULTURECODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CULTURECODE()
        {
            this.GJUHAs = new HashSet<GJUHA>();
        }
    
        public int ID { get; set; }
        public string CultureCode1 { get; set; }
        public string CultureCodeCountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJUHA> GJUHAs { get; set; }
    }
}
