//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GJUHA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GJUHA()
        {
            this.KATEGORIAs = new HashSet<KATEGORIA>();
            this.LLOJI_PAGESES = new HashSet<LLOJI_PAGESES>();
            this.PERDORUESIs = new HashSet<PERDORUESI>();
            this.PRODUKTIs = new HashSet<PRODUKTI>();
        }
    
        public int ID { get; set; }
        public int CultureCodeID { get; set; }
        public string GjuhaEmerimi { get; set; }
        public bool Aktiv { get; set; }
    
        public virtual CULTURECODE CULTURECODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KATEGORIA> KATEGORIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLOJI_PAGESES> LLOJI_PAGESES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERDORUESI> PERDORUESIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKTI> PRODUKTIs { get; set; }
    }
}
