//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KATEGORIA()
        {
            this.PRODUKTI_IN_KATEGORIA = new HashSet<PRODUKTI_IN_KATEGORIA>();
        }
    
        public int ID { get; set; }
        public int GjuhaID { get; set; }
        public string Emertimi { get; set; }
        public string Pershkrimi { get; set; }
        public bool Aktiv { get; set; }
        public Nullable<int> PrindiID { get; set; }
    
        public virtual GJUHA GJUHA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKTI_IN_KATEGORIA> PRODUKTI_IN_KATEGORIA { get; set; }
    }
}
