//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTAKTI
    {
        public int ID { get; set; }
        public string KontaktiPershkrimi { get; set; }
        public string Adresa { get; set; }
        public string Telefoni { get; set; }
        public string Email { get; set; }
        public Nullable<int> MediaID { get; set; }
        public string GPS { get; set; }
    
        public virtual Medium Medium { get; set; }
    }
}
