//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ENTRY
    {
        public int ID { get; set; }
        public int PerdoruesiID { get; set; }
        public int Type { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
