//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medium()
        {
            this.KONTAKTIs = new HashSet<KONTAKTI>();
            this.PRODUKTI_IN_MEDIA = new HashSet<PRODUKTI_IN_MEDIA>();
            this.SLLIDEs = new HashSet<SLLIDE>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> Emri { get; set; }
        public string Extensioni { get; set; }
        public string Pershkrimi { get; set; }
        public System.DateTime Created { get; set; }
        public int Createdby { get; set; }
        public string Shtegu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONTAKTI> KONTAKTIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKTI_IN_MEDIA> PRODUKTI_IN_MEDIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SLLIDE> SLLIDEs { get; set; }
    }
}
