//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKTI_DETAJET
    {
        public int ID { get; set; }
        public int ProduktiID { get; set; }
        public string Kodi { get; set; }
        public decimal CmimiBaze { get; set; }
        public decimal TVSH { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<decimal> Zbritja { get; set; }
    
        public virtual PRODUKTI PRODUKTI { get; set; }
    }
}
