//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKTI_IN_POROSIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUKTI_IN_POROSIA()
        {
            this.KTHIMET_POROSIA = new HashSet<KTHIMET_POROSIA>();
        }
    
        public int ID { get; set; }
        public int PorosiaID { get; set; }
        public int ProduktiID { get; set; }
        public int Sasia { get; set; }
        public decimal CmimiPaTvsh { get; set; }
        public decimal CmimMeTvsh { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KTHIMET_POROSIA> KTHIMET_POROSIA { get; set; }
        public virtual POROSIA POROSIA { get; set; }
        public virtual PRODUKTI PRODUKTI { get; set; }
    }
}
