//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTHIMET_POROSIA
    {
        public int ID { get; set; }
        public int PorosiaProduktiID { get; set; }
        public int PerdoruesiID { get; set; }
        public System.DateTime DataKthimit { get; set; }
        public string Arsyeja { get; set; }
    
        public virtual PERDORUESI PERDORUESI { get; set; }
        public virtual PRODUKTI_IN_POROSIA PRODUKTI_IN_POROSIA { get; set; }
    }
}
