//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NJOFTIMET
    {
        public int ID { get; set; }
        public int FromUserID { get; set; }
        public Nullable<int> ToUserID { get; set; }
        public string FromU { get; set; }
        public string ToU { get; set; }
        public string ToUser { get; set; }
        public System.DateTime Data { get; set; }
        public string Message { get; set; }
        public int Type { get; set; }
    
        public virtual PERDORUESI PERDORUESI { get; set; }
        public virtual PERDORUESI PERDORUESI1 { get; set; }
    }
}
