//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class POROSIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POROSIA()
        {
            this.PRODUKTI_IN_POROSIA = new HashSet<PRODUKTI_IN_POROSIA>();
        }
    
        public int ID { get; set; }
        public int LlojiPagesesID { get; set; }
        public int StatusiPorosiaID { get; set; }
        public int PerdoruesiID { get; set; }
        public System.DateTime DataPorosise { get; set; }
        public Nullable<System.DateTime> DataPageses { get; set; }
        public Nullable<System.DateTime> DataArritjes { get; set; }
        public Nullable<int> CreditCardID { get; set; }
    
        public virtual KARTELA KARTELA { get; set; }
        public virtual LLOJI_PAGESES LLOJI_PAGESES { get; set; }
        public virtual PERDORUESI PERDORUESI { get; set; }
        public virtual STATUSI_PAGESES STATUSI_PAGESES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKTI_IN_POROSIA> PRODUKTI_IN_POROSIA { get; set; }
    }
}
