//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKTI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUKTI()
        {
            this.PRODUKTI_IN_KATEGORIA = new HashSet<PRODUKTI_IN_KATEGORIA>();
            this.PRODUKTI_IN_MEDIA = new HashSet<PRODUKTI_IN_MEDIA>();
            this.PRODUKTI_IN_POROSIA = new HashSet<PRODUKTI_IN_POROSIA>();
            this.STOKUs = new HashSet<STOKU>();
        }
    
        public int ID { get; set; }
        public string Emertimi { get; set; }
        public string Pershkrimi { get; set; }
        public string Kodi { get; set; }
        public int Sasia { get; set; }
        public decimal CmimiBaze { get; set; }
        public Nullable<decimal> TVSH { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<decimal> Zbritja { get; set; }
        public Nullable<int> ProdhuesiID { get; set; }
        public int Statusi { get; set; }
        public Nullable<bool> Perfunduar { get; set; }
    
        public virtual PRODHUESI PRODHUESI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKTI_IN_KATEGORIA> PRODUKTI_IN_KATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKTI_IN_MEDIA> PRODUKTI_IN_MEDIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUKTI_IN_POROSIA> PRODUKTI_IN_POROSIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOKU> STOKUs { get; set; }
    }
}
