//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKTI_IN_MEDIA
    {
        public int ID { get; set; }
        public int ProduktiID { get; set; }
        public int MediaID { get; set; }
    
        public virtual MEDIAT MEDIAT { get; set; }
        public virtual PRODUKTI PRODUKTI { get; set; }
    }
}
