//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLLIDE
    {
        public int ID { get; set; }
        public Nullable<int> MediaID { get; set; }
        public string SllideTitulli { get; set; }
        public string SllidePershkrimi { get; set; }
        public Nullable<System.DateTime> SllideDataInsertimit { get; set; }
        public Nullable<int> OrderNr { get; set; }
        public string Linku { get; set; }
    
        public virtual MEDIAT MEDIAT { get; set; }
    }
}
