//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSMENU_PARENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSMENU_PARENT()
        {
            this.SYSMENUs = new HashSet<SYSMENU>();
        }
    
        public int ID { get; set; }
        public string Pershkrimi { get; set; }
        public string HtmlClass { get; set; }
        public int RoleID { get; set; }
        public int Renditja { get; set; }
        public string styleid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSMENU> SYSMENUs { get; set; }
    }
}
